// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2);
}

export function SavePDF(arg1, arg2) {
  return window['go']['main']['App']['SavePDF'](arg1, arg2);
}

export function SuggestedFilename(arg1) {
  return window['go']['main']['App']['SuggestedFilename'](arg1);
}

export function SaveToDownloads(arg1, arg2) {
  return window['go']['main']['App']['SaveToDownloads'](arg1, arg2);
}
