// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdf} from '../models';

export function ExportPDF(arg1:string,arg2:pdf.Settings):Promise<string>;

export function SavePDF(arg1:string,arg2:string):Promise<string>;

export function SuggestedFilename(arg1:string):Promise<string>;
